spring.application.name=activity_planner

weather.api.key=WEATHER_API_KEY
activity.api.key=ACTIVITY_API_KEY

# Circuit Breaker - Weather Service
resilience4j.circuitbreaker.instances.weather.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.weather.slidingWindowSize=10
resilience4j.circuitbreaker.instances.weather.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.weather.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.weather.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.weather.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.weather.failureRateThreshold=50

# Circuit Breaker - Activities Service
resilience4j.circuitbreaker.instances.activities.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.activities.slidingWindowSize=10
resilience4j.circuitbreaker.instances.activities.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.activities.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.activities.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.activities.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.activities.failureRateThreshold=50

# Time Limiter - Weather Service
resilience4j.timelimiter.instances.weather.timeoutDuration=5s

# Time Limiter - Activities Service
resilience4j.timelimiter.instances.activities.timeoutDuration=5s
